botToken: '5965008171:AAGsp9wshkkBz6pHAZp7EUcRHepIbSJ1mdQ'
botUrl: 'https://t.me/Vpnster_bot'
layoutsPath: 'layouts.yaml'
iokassaToken: '976146:live_5K_OelXbldhwmPK_A2KUV2A2XQT8bH0xIwla92KJkPU'
backend:
  host: '185.41.160.153'
  port: '8083'