<<<<<<< HEAD
﻿botToken: '5965008171:AAGsp9wshkkBz6pHAZp7EUcRHepIbSJ1mdQ'
=======
﻿botToken: '1456257916:AAFXlGP9xZgWEwZzkgtTr03a9M4vZPZ-r2I'
>>>>>>> master
botUrl: 'https://t.me/Vpnster_bot'
layoutsPath: 'layouts.yaml'
iokassaToken: '606187:test_rfWl9R66FvKB3QyzwGlid8deH9YiPcReTgv3r-KFSsA'
backend:
  host: 'localhost'
  port: '8083'
