botToken: '1456257916:AAFXlGP9xZgWEwZzkgtTr03a9M4vZPZ-r2I'
botUrl: 'https://t.me/Vpnster_bot'
layoutsPath: 'layouts.yaml'
iokassaToken: '976146:live_5K_OelXbldhwmPK_A2KUV2A2XQT8bH0xIwla92KJkPU'
backend:
  host: 'localhost'
  port: '8083'